chicago_streets = {'ew': {
-9: {'name': 'Harlem Ave', 'shortname': 'Harlem ', 'number': '7200', 'direction': 'W', 'milemarker': '-9'},
-8.5: {'name': 'Oak Park Ave', 'shortname': 'Oak ', 'number': '6800', 'direction': 'W', 'milemarker': '-8.5'},
-8: {'name': 'Narragansett Ave', 'shortname': 'Narragansett ', 'number': '6400', 'direction': 'W', 'milemarker': '-8'},
-7.5: {'name': 'Austin Ave', 'shortname': 'Austin ', 'number': '6000', 'direction': 'W', 'milemarker': '-7.5'},
-7: {'name': 'Central Ave', 'shortname': 'Central ', 'number': '5600', 'direction': 'W', 'milemarker': '-7'},
-6.5: {'name': 'Laramie Ave', 'shortname': 'Laramie ', 'number': '5200', 'direction': 'W', 'milemarker': '-6.5'},
-6: {'name': 'Cicero Ave', 'shortname': 'Cicero ', 'number': '4800', 'direction': 'W', 'milemarker': '-6'},
-5.5: {'name': 'Kostner Ave', 'shortname': 'Kostner ', 'number': '4400', 'direction': 'W', 'milemarker': '-5.5'},
-5: {'name': 'Pulaski Rd', 'shortname': 'Pulaski ', 'number': '4000', 'direction': 'W', 'milemarker': '-5'},
-4.5: {'name': 'Central Park Ave', 'shortname': 'Central ', 'number': '3600', 'direction': 'W', 'milemarker': '-4.5'},
-4: {'name': 'Kedzie Ave', 'shortname': 'Kedzie ', 'number': '3200', 'direction': 'W', 'milemarker': '-4'},
-3.5: {'name': 'California Ave', 'shortname': 'California ', 'number': '2800', 'direction': 'W', 'milemarker': '-3.5'},
-3: {'name': 'Western Ave', 'shortname': 'Western ', 'number': '2400', 'direction': 'W', 'milemarker': '-3'},
-2.5: {'name': 'Damen Ave', 'shortname': 'Damen ', 'number': '2000', 'direction': 'W', 'milemarker': '-2.5'},
-2: {'name': 'Ashland Ave', 'shortname': 'Ashland ', 'number': '1600', 'direction': 'W', 'milemarker': '-2'},
-1.5: {'name': 'Racine Ave', 'shortname': 'Racine ', 'number': '1200', 'direction': 'W', 'milemarker': '-1.5'},
-1: {'name': 'Halsted St', 'shortname': 'Halsted ', 'number': '800', 'direction': 'W', 'milemarker': '-1'},
-0.5: {'name': 'Wells St', 'shortname': 'Wells ', 'number': '400', 'direction': 'W', 'milemarker': '-0.5'},
0: {'name': 'State St', 'shortname': 'State ', 'number': '0', 'direction': 'W', 'milemarker': '0'},
0.5: {'name': 'Indiana Ave', 'shortname': 'Indiana ', 'number': '400', 'direction': 'E', 'milemarker': '0.5'},
1: {'name': 'Cottage Grove Ave', 'shortname': 'Cottage ', 'number': '800', 'direction': 'E', 'milemarker': '1'},
1.5: {'name': 'Woodlawn Ave', 'shortname': 'Woodlawn ', 'number': '1200', 'direction': 'E', 'milemarker': '1.5'},
2: {'name': 'Stony Island Ave', 'shortname': 'Stony ', 'number': '1600', 'direction': 'E', 'milemarker': '2'},
2.5: {'name': 'Jeffery Blvd', 'shortname': 'Jeffery ', 'number': '2000', 'direction': 'E', 'milemarker': '2.5'},
3: {'name': 'Yates Blvd', 'shortname': 'Yates ', 'number': '2400', 'direction': 'E', 'milemarker': '3'},
4: {'name': 'Avenue L', 'shortname': 'Avenue ', 'number': '3200', 'direction': 'E', 'milemarker': '4'},
5: {'name': 'Avenue O', 'shortname': 'Avenue ', 'number': '4000', 'direction': 'E', 'milemarker': '5'},
}, "ns": {
10: {'name': 'Howard St', 'shortname': 'Howard ', 'number': '8000', 'direction': 'N', 'milemarker': '10'},
9.5: {'name': 'Jarvis Ave', 'shortname': 'Jarvis ', 'number': '7600', 'direction': 'N', 'milemarker': '9.5'},
9: {'name': 'Touhy Ave', 'shortname': 'Touhy ', 'number': '7200', 'direction': 'N', 'milemarker': '9'},
8.5: {'name': 'Pratt Blvd', 'shortname': 'Pratt ', 'number': '6800', 'direction': 'N', 'milemarker': '8.5'},
8: {'name': 'Devon Ave', 'shortname': 'Devon ', 'number': '6400', 'direction': 'N', 'milemarker': '8'},
7.5: {'name': 'Peterson Ave', 'shortname': 'Peterson ', 'number': '6000', 'direction': 'N', 'milemarker': '7.5'},
7: {'name': 'Bryn Mawr Ave', 'shortname': 'Bryn ', 'number': '5600', 'direction': 'N', 'milemarker': '7'},
6.5: {'name': 'Foster Ave', 'shortname': 'Foster ', 'number': '5200', 'direction': 'N', 'milemarker': '6.5'},
6: {'name': 'Lawrence Ave', 'shortname': 'Lawrence ', 'number': '4800', 'direction': 'N', 'milemarker': '6'},
5.5: {'name': 'Montrose Ave', 'shortname': 'Montrose ', 'number': '4400', 'direction': 'N', 'milemarker': '5.5'},
5: {'name': 'Irving Park Rd', 'shortname': 'Irving ', 'number': '4000', 'direction': 'N', 'milemarker': '5'},
4.5: {'name': 'Addison St', 'shortname': 'Addison ', 'number': '3600', 'direction': 'N', 'milemarker': '4.5'},
4: {'name': 'Belmont Ave', 'shortname': 'Belmont ', 'number': '3200', 'direction': 'N', 'milemarker': '4'},
3.5: {'name': 'Diversey Ave', 'shortname': 'Diversey ', 'number': '2800', 'direction': 'N', 'milemarker': '3.5'},
3: {'name': 'Fullerton Ave', 'shortname': 'Fullerton ', 'number': '2400', 'direction': 'N', 'milemarker': '3'},
2.5: {'name': 'Armitage Ave', 'shortname': 'Armitage ', 'number': '2000', 'direction': 'N', 'milemarker': '2.5'},
2: {'name': 'North Ave', 'shortname': 'North ', 'number': '1600', 'direction': 'N', 'milemarker': '2'},
1.5: {'name': 'Division Ave', 'shortname': 'Division ', 'number': '1200', 'direction': 'N', 'milemarker': '1.5'},
1: {'name': 'Chicago Ave', 'shortname': 'Chicago ', 'number': '800', 'direction': 'N', 'milemarker': '1'},
0.5: {'name': 'Kinzie St', 'shortname': 'Kinzie ', 'number': '400', 'direction': 'N', 'milemarker': '0.5'},
0: {'name': 'Madison St', 'shortname': 'Madison ', 'number': '0', 'direction': 'N', 'milemarker': '0'},
-0.5: {'name': 'Harrison St', 'shortname': 'Harrison ', 'number': '600', 'direction': 'S', 'milemarker': '-0.5'},
-1: {'name': 'Roosevelt Rd', 'shortname': 'Roosevelt ', 'number': '1200', 'direction': 'S', 'milemarker': '-1'},
-1.5: {'name': '18th St', 'shortname': '18th ', 'number': '1800', 'direction': 'S', 'milemarker': '-1.5'},
-2: {'name': 'Cermak Rd (22nd St)', 'shortname': 'Cermak ', 'number': '2200', 'direction': 'S', 'milemarker': '-2'},
-2.5: {'name': '26th St', 'shortname': '26th ', 'number': '2600', 'direction': 'S', 'milemarker': '-2.5'},
-3: {'name': '31st St', 'shortname': '31st ', 'number': '3100', 'direction': 'S', 'milemarker': '-3'},
-3.5: {'name': '39th St (Pershing Rd)', 'shortname': '39th ', 'number': '3900', 'direction': 'S', 'milemarker': '-3.5'},
-4: {'name': '47th St', 'shortname': '47th ', 'number': '4700', 'direction': 'S', 'milemarker': '-4'},
-4.5: {'name': '55th St (Garfield Blvd)', 'shortname': '55th ', 'number': '5500', 'direction': 'S', 'milemarker': '-4.5'},
-5: {'name': '63rd St', 'shortname': '63rd ', 'number': '6300', 'direction': 'S', 'milemarker': '-5'},
-5.5: {'name': '71st St', 'shortname': '71st ', 'number': '7100', 'direction': 'S', 'milemarker': '-5.5'},
-6: {'name': '79th St', 'shortname': '79th ', 'number': '7900', 'direction': 'S', 'milemarker': '-6'},
-6.5: {'name': '87th St', 'shortname': '87th ', 'number': '8700', 'direction': 'S', 'milemarker': '-6.5'},
-7: {'name': '95th St', 'shortname': '95th ', 'number': '9500', 'direction': 'S', 'milemarker': '-7'},
-7.5: {'name': '99th St', 'shortname': '99th ', 'number': '9900', 'direction': 'S', 'milemarker': '-7.5'},
-8: {'name': '103rd St', 'shortname': '103rd ', 'number': '10300', 'direction': 'S', 'milemarker': '-8'},
}}